from .report_repository_interface import ReportRepositoryInterface
from .user_repository_interface import UserRepositoryInterface
from .department_repository_interface import DepartmentRepositoryInterface